# Generated by Django 4.1.1 on 2022-11-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('bankname', models.CharField(max_length=50)),
                ('transactionid', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
